### ISSUE TITLE
Test artifacts is locked on filesystem

### ISSUE THREAD

**Issue by ThomasSkelgaard** [gocd/gocd.github.io#236]
After upgrading to 15.3 the test artifacts from working dir on agent is locker after stage is finish. The next stage will then fail as it is not able to clean working directory.

Sometime the files are unlocked after a long time or the Go Agent needs to be re-started to free the filelock.

Is this a known issue?

Stage that complete but seems to lock file
![gostagethatlock](https://cloud.githubusercontent.com/assets/6838005/11975183/644638c6-a96b-11e5-873b-9d287f4bc916.jpg)

The stage right after that cannot do a clean
![go](https://cloud.githubusercontent.com/assets/6838005/11975137/0d942f74-a96b-11e5-8dc9-38e407d38f47.jpg)

**Comment by ketan** [comment]
Can you open this issue against the gocd/gocd repository? This repository
is for the main go.cd website

**Comment by ThomasSkelgaard** [comment]
Sorry. I have created a new one.
