### ISSUE TITLE
Automated install on windows

### ISSUE THREAD

**Issue by swade1987** [gocd/gocd.github.io#255]
I am trying to look for either a Chef cookbook or create my own to automate the install of both the server and agent on windows.

**Comment by ketan** [comment]
@swade1987 — this is the repo for gocd's website.

Windows cookbook support is here — https://github.com/gocd-contrib/go-cookbook/pull/66 if you want to try it out and submit an issue.

I plan on releasing the cookbook in a couple of days is you can confirm that it works for you.
