### ISSUE TITLE
Lazy Load or Optional Artifacts Tab on Job view

### ISSUE THREAD

**Issue by dragoon20** [gocd/gocd.github.io#268]
If the artifacts are large enough, it will cause, viewing the job details in GoCD to be slow enough and not effective for developers.

**Comment by zabil** [comment]
@dragoon20 this is the repo for gocd website.

Please use https://github.com/gocd/gocd/issues for creating feature requests.
 
Also replace vague generalizations like "large enough", "slow enough" and "not effective" by providing more information.

**Comment by dragoon20** [comment]
thanks @zabil , will do
