### ISSUE TITLE
Add option to make a task not important

### ISSUE THREAD

**Issue by dragoon20** [gocd/gocd.github.io#269]
Sometimes a task, doesn't really matter to the result.
Example: if fetch artifacts failed, the job should still be able to succeed.

**Comment by zabil** [comment]
@dragoon20 the tasks must be predictable, especially the "Fetch artifacts" task. 
Failing to download artifacts from an upstream pipeline indicates failure. 

For other tasks we suggest using the right exit code to handle the not important conditions.
